site_name: lobu
site_description: lobu resources
repo_url: https://github.com/vimagox/lobu-api
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/vimagox">vimagox</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
